### ISSUE TITLE
Needs updating 

### ISSUE THREAD

**Issue by randstrom** [Tecnologica-Mente/Pearson_DRM_Remover#1]
The following needs to change:

https://api.pearson.com/v1/piapi/login/webcredentials

to this:

https://login.pearson.com/v1/piapi/login/webcredentials

Further, the download function doesn’t seem to work. The server replies with “invalid” something or other.  See device_info.

**Comment by Tecnologica-Mente** [comment]
Hi friend, thank you, change done! ;-)
I thanked you in the affected file.
